### ISSUE TITLE
Appropriate Numbering System

### ISSUE THREAD

**Issue by davidtwco** [TartanLlama/secret-hitler-strategies#36]
I think it is imperative that each section and subsection is appropriately numbered such that the strategy guide can be referred to as follows:

`I think you'll find in subsection 3a of section 4, the strategy states...`

or

`He's clearly playing the strategy in section 5c, there's no doubt.`

It is obvious that this would be an immeasurable improvement to the strategy guide.

**Comment by TartanLlama** [comment]
Yesyesyes.
