### ISSUE TITLE
Rework document structure

### ISSUE THREAD

**Issue by 7thsanctum** [TartanLlama/secret-hitler-strategies#4]
The current version is quite hard to read and absorb. It would be good to restructure the document so it reads linearly better from start to finish. This way you could hand this to someone and they get an idea of how to play without being swamped with too much advanced strategy.

Something like this perhaps:
1. Introduction
2. Setting Up
3. Basic Strategy as Liberal, Fascist or Hitler
4. Irrefutable observations/strategy
5. Advanced Strategy
6. Experimental Strategy 

This way you could read sections 1 - 3 before a game followed by the remaining sections. More discussion is needed for this.

**Comment by NeuralSandwich** [comment]
* Should a Table of content be added?
* Section headers should be anchored if they currently aren't

**Comment by 7thsanctum** [comment]
I think a table of contents could be handy for jumping down the page.
I don't think they are anchored, I agree they should be.

**Comment by TartanLlama** [comment]
I like the structure you suggested. I also like having tactics for each stage of the game like we have now. Maybe there's a way we can integrate the two ideas?

**Comment by 7thsanctum** [comment]
For the main document and page we could have it as an overview. We could then have a second document/page that describes the full order of play and our observations at different stages.

For example, we could highlight what certain patterns of yes/no mean at different stages. Our suspicions, votes leading up to brexit in certain rounds when certain policies are down.

I can imagine that being quite long so a separate file could be sensible.

**Comment by TartanLlama** [comment]
Another idea is that if the strategies and tactics are clearly delimited, the order-of-play section could reference the strategies with links.

### Voting
#### As liberal

- Strat 1 link
- Strat 2 link

#### As fascist
- Strat 1 link

**Comment by TartanLlama** [comment]
Anyone want to have a bash at this?
