### ISSUE TITLE
Mention anti-clockwise chancellor rule

### ISSUE THREAD

**Issue by TartanLlama** [TartanLlama/secret-hitler-strategies#49]
We usually nominate the person to our right as the chancellor. We should mention this and describe the reasoning behind it.

**Comment by 7thsanctum** [comment]
I just added an extra line about how the presidential nominations mean someone can be president twice. I like the way the current rules are setup so they don't confuse you with extra strategy. Is it worth however trying to link these up with a link to "advanced nomination tactics"?

**Comment by TartanLlama** [comment]
It could be, maybe
