### ISSUE TITLE
Add table of probabilities at certain stages in the game

### ISSUE THREAD

**Issue by 7thsanctum** [TartanLlama/secret-hitler-strategies#61]
It would be interesting to know different probabilities of certain card draws at different stages. I've been putting in some effort to try and understand them and how different odds stack and affect each other. This might need its own dedicated page since depending on what is played that will affect how you can calculate how likely something is to happen next.

Initially it would be good to know the odds on the draw. For example, drawing a single card from a deck of 17 (where 6 are Liberal and 11 are Fascist) the chance of it being Liberal is 35.3%. However, the chance of AT LEAST one being Liberal jumps up to 75% when you draw 3 times.

I'll sit down and write this up at some point but if anyone has any feedback to ensure my numbers are correct let me know. I originally tried to do it by hand but I'm using this hypergeometric distribution calculator now instead : http://stattrek.com/online-calculator/hypergeometric.aspx

I'll write up a table soon

**Comment by 7thsanctum** [comment]
I've created a table here : https://docs.google.com/spreadsheets/d/1i7PTPCtSM6hDCxXgFCAvw-T7AGpmd2QkHupyO7HjkV0/edit?usp=sharing

My issue now is trying to work out how to display and how to make it most readable. What I was thinking is some kind of lookup table with all the precalculated probabilities. This way if you know the number of cards in the deck you can work out the likelihood of certain scenarios.

**Comment by TartanLlama** [comment]
@7thsanctum are you planning to add your data to the site at some point?

**Comment by 7thsanctum** [comment]
Yes sorry I plan to add this @TartanLlama I've just been pretty busy so I haven't had a chance to sit down and do this. I will get to it ASAP

**Comment by TartanLlama** [comment]
@7thsanctum maaaaaaaaark

**Comment by TartanLlama** [comment]
@7thsanctum maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaark
