### ISSUE TITLE
Consider mentioning a "no direct questioning" option under Etiquette?

### ISSUE THREAD

**Issue by chrisblakley** [TartanLlama/secret-hitler-strategies#66]
The only house rule that I employ for all deception games is that players are not allowed to directly ask "Are you a fascist?" to a player face-to-face. I've played with lots of people who have a bad poker face, but otherwise have brilliant strategies which gets undermined when someone asks the directly until they break.

We have no problems yelling at and accusing each other, but I wanted to share this as a possible addition to the Etiquette section for others to consider if they have trouble.

**Comment by TartanLlama** [comment]
Thanks for the suggestion! I've pushed a fix for this.
